Fix hook exit on error

diff --git a/hooks/build b/hooks/build
--- a/hooks/build
+++ b/hooks/build
@@ -1,4 +1,6 @@
 #!/bin/bash
+# Exit on error
+set -e
 
 echo "Running build hook !"
 TAG_COMMAND="-t $IMAGE_NAME"
diff --git a/hooks/push b/hooks/push
--- a/hooks/push
+++ b/hooks/push
@@ -1,4 +1,6 @@
 #!/bin/bash
+# Exit on error
+set -e
 
 echo "Running push hook !"
 echo "Pushing every tag for docker repo $DOCKER_REPO"
